"""
Extension 5 — Synthetic SFT Data Generation.

Motivation
----------
hh-rlhf provides ~42k human-written (prompt, chosen-response) pairs.  But human
annotation is expensive and biased toward the prompts that Anthropic happened to
collect.  A *synthetic* SFT dataset generated by a strong LLM can be:

  1. Arbitrarily large — no human bottleneck
  2. Diverse — systematic coverage of topic categories, difficulty, tone
  3. Constitution-grounded — every response is explicitly written to satisfy a
     set of principles, so the SFT policy absorbs those values from day one

Pipeline
--------
  1. Draw a prompt from a seed bank (or generate one via Claude)
  2. Ask Claude to write an ideal response grounded in a SFT constitution
  3. (Optional) apply a critic pass: ask Claude to critique and revise the response
  4. Write (prompt, response) pairs to JSONL for fine-tuning

Ablation
--------
Fine-tune GPT-2-medium on three data sources and compare RM-judged preference accuracy:
  A. hh-rlhf chosen responses    (human baseline, ~10k examples)
  B. Synthetic SFT from Claude   (same 10k budget, constitution-grounded)
  C. Mixed 50/50                 (best of both worlds)

Expected finding: synthetic data reaches within 2–3 pp of human-data SFT quality,
and mixing the two datasets beats either alone.
"""

from __future__ import annotations

import json
import os
import random
import re
import time
from dataclasses import dataclass, field
from pathlib import Path
from typing import Dict, List, Optional, Tuple

import torch
from torch.utils.data import Dataset
from transformers import PreTrainedTokenizer

# ── Constitution for SFT response generation ─────────────────────────────────

SFT_CONSTITUTION: List[str] = [
    "Be genuinely helpful: directly answer what is asked without unnecessary hedging.",
    "Be honest: acknowledge uncertainty, do not fabricate facts or citations.",
    "Be harmless: do not provide instructions that could endanger the user or others.",
    "Be clear: use concrete language, logical structure, and appropriate examples.",
    "Respect autonomy: do not lecture or moralize beyond what is directly relevant.",
    "Be concise: avoid padding, hollow affirmations, or repeating the question.",
    "Be complete: give enough detail that the user can act on the answer.",
]

# ── Prompt seed bank ──────────────────────────────────────────────────────────

PROMPT_CATEGORIES = {
    "factual": [
        "What is the difference between supervised and unsupervised learning?",
        "How does gradient descent work?",
        "Explain the attention mechanism in transformers.",
        "What is the Central Limit Theorem and why does it matter?",
        "How do vaccines trigger an immune response?",
        "What causes inflation and how do central banks respond?",
        "Explain the difference between TCP and UDP protocols.",
        "What is a hash function and where is it used in practice?",
    ],
    "creative": [
        "Write a short poem about learning from failure.",
        "Describe a futuristic city where AI assists humans in daily tasks.",
        "Write a 200-word story that begins with 'The algorithm was wrong.'",
        "Compose a haiku about debugging code.",
    ],
    "reasoning": [
        "Is it ethical to trade off privacy for convenience? Argue both sides.",
        "Should social media platforms be regulated like utilities? Give a reasoned answer.",
        "A company promises 'AI that is always right.' What should make you skeptical?",
        "Is open-sourcing powerful AI models net-positive or net-negative? Why?",
    ],
    "instructional": [
        "How do I set up a Python virtual environment and manage dependencies?",
        "Walk me through training a logistic regression classifier from scratch.",
        "How do I profile a slow Python function to find the bottleneck?",
        "Explain how to do a code review effectively as a senior engineer.",
        "How do I write a unit test for a function with side effects?",
    ],
    "conversational": [
        "I'm feeling overwhelmed by how much I have to learn. Any advice?",
        "What's a good approach to staying up to date in a fast-moving field like AI?",
        "How do you decide when a project is 'good enough' to ship?",
        "What makes a great mentor-mentee relationship in engineering?",
    ],
}

ALL_SEED_PROMPTS: List[str] = [
    p for prompts in PROMPT_CATEGORIES.values() for p in prompts
]


# ── Synthetic generation ──────────────────────────────────────────────────────

def _build_synthetic_sft_prompt(
    user_prompt: str,
    constitution: List[str],
    apply_critic: bool = False,
    draft_response: Optional[str] = None,
) -> str:
    """Build the Claude API prompt for generating an ideal SFT response."""
    principles = "\n".join(f"  {i+1}. {p}" for i, p in enumerate(constitution))

    if apply_critic and draft_response:
        return (
            "You are a careful AI assistant.  You wrote a draft response to a user's "
            "message.  Please critique the draft against the principles below, then "
            "write a revised, improved response.\n\n"
            f"Principles:\n{principles}\n\n"
            f"User message:\n{user_prompt}\n\n"
            f"Draft response:\n{draft_response}\n\n"
            "First write CRITIQUE: [one sentence identifying the main weakness]\n"
            "Then write REVISED RESPONSE:\n[your improved response]\n"
        )

    return (
        "You are a helpful, honest, and harmless AI assistant.  Write an ideal "
        "response to the following user message.  Your response must satisfy all "
        "of the principles below.\n\n"
        f"Principles:\n{principles}\n\n"
        f"User message:\n{user_prompt}\n\n"
        "Response:\n"
    )


def generate_synthetic_sft_pair(
    client,
    user_prompt: str,
    constitution: List[str] = SFT_CONSTITUTION,
    model: str = "claude-haiku-4-5-20251001",
    max_tokens: int = 400,
    apply_critic: bool = True,
    retry_on_error: bool = True,
) -> Dict[str, str]:
    """Generate a single (prompt, ideal_response) pair grounded in the constitution.

    Parameters
    ----------
    client:
        Initialised ``anthropic.Anthropic()`` client.
    user_prompt:
        The instruction / conversation turn to respond to.
    constitution:
        List of principles the response must satisfy.
    apply_critic:
        If True, do a two-pass generation: draft → critique → revised response.
        Adds one extra API call but improves quality.

    Returns
    -------
    dict with:
        prompt          : the original user message
        response        : the ideal response (revised if apply_critic=True)
        model           : which Claude model generated it
        critic_applied  : whether the critic pass was run
    """
    # Pass 1: generate draft response
    draft_prompt = _build_synthetic_sft_prompt(user_prompt, constitution, apply_critic=False)

    for attempt in range(3 if retry_on_error else 1):
        try:
            resp = client.messages.create(
                model=model,
                max_tokens=max_tokens,
                messages=[{"role": "user", "content": draft_prompt}],
            )
            draft = resp.content[0].text.strip()
            break
        except Exception as e:
            if attempt == 2:
                raise
            time.sleep(2 ** attempt)

    if not apply_critic:
        return {
            "prompt": user_prompt,
            "response": draft,
            "model": model,
            "critic_applied": False,
        }

    # Pass 2: critique and revise
    critic_prompt = _build_synthetic_sft_prompt(
        user_prompt, constitution, apply_critic=True, draft_response=draft
    )
    for attempt in range(3 if retry_on_error else 1):
        try:
            resp2 = client.messages.create(
                model=model,
                max_tokens=max_tokens + 100,
                messages=[{"role": "user", "content": critic_prompt}],
            )
            critic_text = resp2.content[0].text.strip()
            break
        except Exception as e:
            if attempt == 2:
                return {
                    "prompt": user_prompt,
                    "response": draft,
                    "model": model,
                    "critic_applied": False,
                }
            time.sleep(2 ** attempt)

    # Extract revised response (after "REVISED RESPONSE:")
    revised_match = re.search(
        r"REVISED RESPONSE:\s*(.+)", critic_text, re.IGNORECASE | re.DOTALL
    )
    revised = revised_match.group(1).strip() if revised_match else draft

    return {
        "prompt": user_prompt,
        "response": revised,
        "draft": draft,
        "model": model,
        "critic_applied": True,
    }


# ── Batch generation pipeline ─────────────────────────────────────────────────

@dataclass
class SyntheticSFTConfig:
    output_path: str = "data/synthetic_sft.jsonl"
    num_samples: int = 2_000
    model: str = "claude-haiku-4-5-20251001"
    max_tokens: int = 400
    apply_critic: bool = True
    requests_per_minute: int = 40
    seed: int = 42
    # Optionally augment the seed bank with Claude-generated prompts
    generate_extra_prompts: bool = True
    extra_prompt_categories: List[str] = field(
        default_factory=lambda: ["factual", "instructional", "reasoning"]
    )


def generate_synthetic_sft_dataset(cfg: SyntheticSFTConfig) -> None:
    """Generate a JSONL file of (prompt, response) pairs via Claude.

    Prompts are drawn from the seed bank (with repetition if needed) and
    optionally augmented with Claude-generated prompt variations.

    The resulting JSONL file has the same schema as hh-rlhf chosen responses
    so :class:`SFTDataset` can load it transparently.
    """
    import anthropic
    from tqdm.auto import tqdm

    client = anthropic.Anthropic()
    rng = random.Random(cfg.seed)
    rate_delay = 60.0 / cfg.requests_per_minute

    # Build prompt pool
    prompts = list(ALL_SEED_PROMPTS)
    if cfg.generate_extra_prompts:
        extra = _generate_extra_prompts(client, cfg, rng)
        prompts.extend(extra)
        print(f"Prompt pool: {len(ALL_SEED_PROMPTS)} seed + {len(extra)} generated = {len(prompts)}")

    os.makedirs(os.path.dirname(cfg.output_path) or ".", exist_ok=True)
    results = []

    pbar = tqdm(range(cfg.num_samples), desc="Generating synthetic SFT pairs")
    for i in pbar:
        prompt = rng.choice(prompts)
        # Light variation: wrap in conversational framing
        if rng.random() < 0.3:
            prompt = _vary_prompt(prompt, rng)

        try:
            pair = generate_synthetic_sft_pair(
                client, prompt,
                model=cfg.model,
                max_tokens=cfg.max_tokens,
                apply_critic=cfg.apply_critic,
            )
            results.append(pair)
            pbar.set_postfix({"critic": pair["critic_applied"]})
        except Exception as e:
            pbar.set_postfix({"error": str(e)[:50]})
            continue

        time.sleep(rate_delay)

    with open(cfg.output_path, "w") as f:
        for item in results:
            f.write(json.dumps(item) + "\n")

    print(f"\nGenerated {len(results)} synthetic SFT pairs → {cfg.output_path}")
    critic_count = sum(1 for r in results if r.get("critic_applied", False))
    print(f"  Critic pass applied: {critic_count}/{len(results)}")


def _generate_extra_prompts(client, cfg: SyntheticSFTConfig, rng: random.Random) -> List[str]:
    """Ask Claude to generate diverse prompt variations for each category."""
    extra = []
    for category in cfg.extra_prompt_categories:
        seed_examples = "\n".join(
            f"  - {p}" for p in PROMPT_CATEGORIES.get(category, [])[:4]
        )
        meta_prompt = (
            f"Generate 10 diverse, specific '{category}' questions or instructions "
            f"that a user might send to an AI assistant.  Each should be on a different "
            f"topic from the examples below.\n\n"
            f"Example questions:\n{seed_examples}\n\n"
            f"Output format: one question per line, no numbering, no explanations."
        )
        try:
            resp = client.messages.create(
                model=cfg.model,
                max_tokens=300,
                messages=[{"role": "user", "content": meta_prompt}],
            )
            lines = resp.content[0].text.strip().split("\n")
            extra.extend([l.strip("- ").strip() for l in lines if l.strip()])
            time.sleep(1.0)
        except Exception:
            pass
    return extra


def _vary_prompt(prompt: str, rng: random.Random) -> str:
    """Lightly rephrase a prompt to add diversity."""
    prefixes = [
        "Can you explain: ",
        "I'd like to understand: ",
        "Help me with this: ",
        "Quick question — ",
        "I'm curious about this: ",
    ]
    return rng.choice(prefixes) + prompt.lower()


# ── Dataset class ─────────────────────────────────────────────────────────────

class SyntheticSFTDataset(Dataset):
    """SFT dataset backed by Claude-generated (prompt, response) pairs.

    Drop-in compatible with :class:`src.data.preprocessing.SFTDataset`:
    produces ``input_ids`` and ``labels`` tensors with prompt tokens masked.
    """

    def __init__(
        self,
        jsonl_path: str,
        tokenizer: PreTrainedTokenizer,
        max_length: int = 512,
    ) -> None:
        self.tokenizer = tokenizer
        self.max_length = max_length
        self.data: List[Dict] = []

        with open(jsonl_path) as f:
            for line in f:
                item = json.loads(line)
                if item.get("response"):
                    self.data.append(item)

        print(f"Loaded {len(self.data)} synthetic SFT pairs from {jsonl_path}")

    def __len__(self) -> int:
        return len(self.data)

    def __getitem__(self, idx: int) -> Dict[str, torch.Tensor]:
        item = self.data[idx]
        prompt = f"Human: {item['prompt']}\n\nAssistant: "
        response = item["response"]
        full_text = prompt + response

        enc = self.tokenizer(
            full_text,
            max_length=self.max_length,
            truncation=True,
            padding="max_length",
            return_tensors="pt",
        )
        input_ids = enc["input_ids"].squeeze(0)
        attention_mask = enc["attention_mask"].squeeze(0)

        # Mask prompt tokens in labels so loss only flows through response
        prompt_enc = self.tokenizer(
            prompt, max_length=self.max_length, truncation=True, return_tensors="pt"
        )
        prompt_len = prompt_enc["input_ids"].shape[1]

        labels = input_ids.clone()
        labels[:prompt_len] = -100  # ignore prompt tokens
        labels[attention_mask == 0] = -100  # ignore padding

        return {
            "input_ids": input_ids,
            "attention_mask": attention_mask,
            "labels": labels,
        }
